fix: Use persistentPeerStore factory method
Resolves errors like below from running `pnpm install`:
```
test/utils/create-pubsub.ts:7:10 - error TS2724: '"@libp2p/peer-store"' has no exported member named 'PersistentPeerStore'. Did you mean 'persistentPeerStore'?

7 import { PersistentPeerStore } from '@libp2p/peer-store'
           ~~~~~~~~~~~~~~~~~~~

  node_modules/.pnpm/@libp2p+peer-store@11.1.3/node_modules/@libp2p/peer-store/dist/src/index.d.ts:46:25
    46 export declare function persistentPeerStore(components: PersistentPeerStoreComponents, init?: PersistentPeerStoreInit): PeerStore;
                               ~~~~~~~~~~~~~~~~~~~
    'persistentPeerStore' is declared here.
```